package dependencies

object Versions {
    const val gradle = "4.2.0-alpha14"
    val compileSdkVersion = 30
    val buildToolsVersion = "30.0.2"
    val minSdkVersion = 21
    val targetSdkVersion = 29
    val kotlin = "1.3.61"
    const val ktx = "1.2.0"
    val dagger = "2.25.4"
    val nav_components = "2.3.0-alpha06"
    val material_dialogs = "3.2.1"
    val room = "2.1.0"
    val appcompat = "1.1.0-rc01"
    val constraintlayout = "1.1.3"
    val material_design = "1.1.0"
    val play_core = "1.7.1"
    const val play_services = "4.3.3"
    val leak_canary = "2.0-alpha-3"
    val swipe_refresh_layout = "1.1.0-alpha03"
    const val firebase_firestore = "21.4.2"
    const val firebase_analytics = "17.4.1"
    const val firebase_crashlytics = "17.0.0"
    const val firebase_auth = "19.3.0"
    val espresso_core = "3.1.1"
    val espresso_idling_resource = "3.2.0"
    val mockk_version = "1.9.2"
    val test_runner = "1.2.0"
    val test_core = "1.2.0"
    const val coroutines_version = "1.4.0-M1"
    const val coroutines_play_services = "1.4.0-M1"
    const val kotlinx_coroutines_test = "1.4.0-M1"
    val lifecycle_version = "2.2.0-alpha03"
    val retrofit2_version = "2.6.0"
    val markdown_processor = "0.1.3"
    val junit_jupiter_version = "5.6.0"
    val junit_4_version = "4.12"
    val fragment_version = "1.2.0"
    val androidx_test_ext = "1.1.1"
    val fabric_version = "1.31.2"
    const val crashlytics_gradle = "2.1.0"
}